[project]
name = "zero"
version = "0.1.0"
description = ""
authors = [
    {name = "suspe",email = "davidp.info1@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[tool.poetry]
packages = [{include = "zero", from = "src"}]


[tool.poetry.group.test.dependencies]
pytest = "^8.4.1"


[tool.poetry.group.dev.dependencies]
setuptools = "^80.9.0"
black = "^25.1.0"
mypy = "^1.17.1"
pre-commit = "^4.2.0"

[tool.mypy]
check_untyped_defs = true

[[tool.mypy.overrides]]
module = ["untyped_package.*"]
follow_untyped_imports = true

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
