# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Python package
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: pre-commit
        run: |
          SKIP=no-commit-to-branch uv run pre-commit run --all-files
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: ${{ github.event_name == 'pull_request' }}
          prerelease: true
          name: "${{ github.ref }}-${{ github.sha }}"
          fail_on_unmatched_files: true
          files: dist/*
